# Generated by Django 3.1.6 on 2021-02-09 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210209_1215'),
    ]

    operations = [
        migrations.DeleteModel(
            name='myModel',
        ),
    ]
